### ISSUE TITLE
Provide guidance on prerequisite for installing abn

### ISSUE THREAD

**Issue by abhishektiwari** [furrer-lab/abn#114]
I faced several issues to install `abn` on both Mac 14.4.1 (M2) and Ubuntu 22.04 due to missing prerequisite packages. Please provide prerequisite guidance for users on Linux, Mac and Windows.

In case of Ubuntu 22.04, I have to install `cmake` `r-cran-rcpp` `r-cran-rcppeigen ` `r-cran-rjags` `libgsl-dev` (after several trial and error) still no luck. Basically, installation instructions don't work out of box. 

[For JOSS Review](https://github.com/openjournals/joss-reviews/issues/6822)

**Comment by j-i-l** [comment]
Hey @abhishektiwari,

were you able to finish the installation process with the provided information? Let us know if you encountered some further roadblocks, or if you think we should detail the installation process more in-depth.

**Comment by abhishektiwari** [comment]
@j-i-l I have to try again given authors have updated the he installation instructions but last I tried it did not work.

**Comment by abhishektiwari** [comment]
@matteodelucchi thanks. I will give a try in next few days.

**Comment by abhishektiwari** [comment]
Unable to complete INLA installation on Mac and Ubuntu. No progress on installing `abn` so far. I am ok to not re-open this ticket in favour of other open tickets.
