### ISSUE TITLE
Streamline versioning process

### ISSUE THREAD

**Issue by j-i-l** [furrer-lab/abn#12]
Currently we have multiple locations where we need to set the version manually (`DESCRIPTION`, `News.md`, `configure` and `configure.ac`, _others?_) in addition to the version we set via `git tag`.

The goal would be to streamline the process of bumping the version, ideally designating one source for the version and have all other mentions be generated automatically.

As @matteodelucchi pointed out, [usethis::use_version()](https://usethis.r-lib.org/reference/use_version.html) might be a solution.
If there does not exist an implementation already that suites our needs, we might also implement this via templating (e.g. with https://github.com/davidchall/jinjar/).

In addition to streamlining the version-bumping process we might also consider to adhere to [semver](https://semver.org/) versioning scheme.

## Steps

1. Evaluate if [usethis::use_version()](https://usethis.r-lib.org/reference/use_version.html) allows to fetch the the version number from a git tag and set it in every location we mention the package version.
2. Implement the process of setting the version number based on the last git tag. (Either with usethis::use_version() or from scratch)

**Comment by matteodelucchi** [comment]
also think about when to recompile vignettes...

**Comment by matteodelucchi** [comment]
> also think about when to recompile vignettes...

see discussion here: https://github.com/furrer-lab/abn/pull/14#discussion_r1536809909

**Comment by matteodelucchi** [comment]
Ideas:
- usethis::use_version()
- if not working, make template of all affected files and make a workflow that creates the final files. Use header with "this file was generated by...".

Decision "versioning workflow":
- use git tag with version number (`git tag v3.0.6-alpha -m "v3.0.6-alpha"`) which triggers workflow to adapt the respective files as nessary.
- if git tag has new patch, this triggers a workflow for a new github release (`git tag v3.0.6 -m "v3.0.6"`).
3.0.5 (github release, CRAN release) -> 3.0.6-alpha (git tag) -> 3.0.6-beta (git tag) -> ... -> 3.0.6 (github release, CRAN release)
- if CRAN returns with cosmetic issues (no new patch), we overwrite the github release. 
3.0.6 -> release CRAN comes back with cosmetic changes -> CRAN release with those fixed keeps same version number (3.0.6 is being overwritten).
- if CRAN returns with issues, issues from s.w. else are reported or if new function in package, then make a new patch version. 
- It is possible that the versions on CRAN are not continuous. Namely, when CRAN reports back a missing functionality, which requires a patch increase, one patch will be skipped on CRAN.
- On Github all patches are available as Github releases and all development versions are available as tags.
- Make automatically new tag upon a push into main branch. Use same semantic as in `r-containers` which allows to specify the tag in the commit message of the pull request.

**Comment by matteodelucchi** [comment]
`usethis::use_version()` doesn't do what we need. It doesn't change the date and adds an empty header to the `NEWS.md`. 

Decision: 
- Use manual adaptation workflow:
   - we trigger a version upgrade with setting a local tag marked as release candidate (e.g. `3.0.7-alpha?`).
   Push this tag to main branch on GH. 
   A new tag on GH main starts the CRAN-like tests and upon successful completion it sets a new tag without the `-alpha`.
      this changes: 
      - DESCRIPTION: update version and date field
      - NEWS: change last header by removing `-alpha` or add additional header with version w/o `rc` as "empty" section to the news file. Even better, check if last title corresponds to version increase.
      - configure.ac: update version number
