### ISSUE TITLE
INLA Package not in CRAN

### ISSUE THREAD

**Issue by dhvalden** [furrer-lab/abn#124]
Installation stops with error: `Error: package 'INLA' is not available`

available from another repo here: https://www.r-inla.org/download-install

Need to be added to the installation. 

either is included to install automatically or deleted from the dependencies, Otherwise the installation will keep stopping with error code.

**Comment by abhishektiwari** [comment]
+1, unable to complete INLA installation on Mac and Ubuntu. No progress on installing `abn` so far.
