### ISSUE TITLE
Add urlchecks to the tests

### ISSUE THREAD

**Issue by j-i-l** [furrer-lab/abn#13]
This is related to #9 

We include sanity checks on URL's/URI's into the testing procedure, also because CRAN does the same when a package is submitted.

The check can be performed with https://github.com/r-lib/urlchecker which might even update permanent redirects (301s).

As such sanity checks are generally relevant, the installation of https://github.com/r-lib/urlchecker should happen in the testing container already, therefore this issue relies on the resolution of https://github.com/furrer-lab/r-containers/issues/21

**Comment by j-i-l** [comment]
add also to CRAN like tests

**Comment by j-i-l** [comment]
add onlz to CRAN like actoin workflow and remove from quick tests

**Comment by matteodelucchi** [comment]
Here are more things to check for CRAN submission: e.g. spellcheck https://github.com/ThinkR-open/prepare-for-cran

**Comment by j-i-l** [comment]
> add onlz to CRAN like actoin workflow and remove from quick tests

Forgot to move the checks to the CRAN like pipeline... :expressionless:
