### ISSUE TITLE
extend SystemRequirements without changes in r-system-requirements package

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#141]
Try to add binaries that are required by:

- [x] INLA
- [x] GSL (check if pattern in `abn` DESCRIPTION is recognised correctly)
- [x] cmake (evtl. gcc, gcc-c++, gfortran, ...)
- [x] JAGS (only Ubuntu for the moment, because other flavours require [modifications in the r-system-requirements rule for JAGS](https://github.com/rstudio/r-system-requirements/pull/169))

**Comment by j-i-l** [comment]
Using `pak` we utilize the SystemRequirements.

For Ubuntu all of the dependencies can be installed, Fedora still needs manual install of `JAGS` (since it needs to be installed from source) and for MacOS and Windows we still need to install the system dependencies manually beforehand.
