### ISSUE TITLE
Issues when trying to control for overfitting.

### ISSUE THREAD

**Issue by brunoholiva** [furrer-lab/abn#162]
I can successfully reproduce results using public datasets, but I am facing problems with my own data. Here are the specific issues I am encountering when I try to adjust for overfitting.

When trying with JAGS and a BUG model - Invalid Parent Values Error: When using the BUG model, I receive an "Invalid Parent Values" error for one of the nodes.

when using mcmcabn() - While employing the mcmcabn() function for structure learning, the search process eventually returns an error: "new.parent.j not found."

I do not come from a statistics or programming field, so I might be overlooking simple and dumb things. My dataset is small (41 observations, 14 variables), but even if this is the problem, I'd like to know what specifically is causing this, and I couldn't find any clear solutions. I've attatched the rdata, R code, and the bug model I've used. Thanks in advance

[ABN.zip](https://github.com/user-attachments/files/17452964/ABN.zip)

**Comment by matteodelucchi** [comment]
I just had a quick look at it. 
- I did not find what caused the issue JAGS at first sight. 
- Did you try to turn off MBR moves in `mcmcabn`? You can do this by setting the probability to zero with `prob.mbr = 0`. Of course, this is only a workaround... Beware, `mcmcabn` would require some polishing and better maintenance, but unfortunately, we don't have the capacity for this at the moment...
