### ISSUE TITLE
documentation of the testing procedure

### ISSUE THREAD

**Issue by j-i-l** [furrer-lab/abn#24]
- the usage of r-containers
  - how to change container tag
  - note that `latest` containers are updated each month

Add section to README (subsection of contributing) Development Environment and Testing

**Comment by matteodelucchi** [comment]
Here's a good resource describing "best practices": https://devguide.ropensci.org/maintenance_collaboration.html

**Comment by j-i-l** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by j-i-l** [comment]
Done in https://github.com/furrer-lab/abn/pull/82
