### ISSUE TITLE
implement automatic recompilation of the vignettes

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#50]
Think about how to incorporate this in the pipeline.

**Comment by j-i-l** [comment]
this belongs to #81

**Comment by matteodelucchi** [comment]
Process: `.Rmd.orig` -- calc --> `.Rmd` -- render --> `.html`
render is performed by pkgdown, testthat and CRAN checks.
calc is performed by `precompile.R`. 

To be implemented:
Workflow that is triggered on the label that sources `precompile.R`. Then, the `.Rmd` files should be committed to the current branch (this is a dev-branch or the release branch when the "release" workflow sets the label).

**Comment by matteodelucchi** [comment]
consider to use the abn container to avoid installing arbitrary package versions.
