### ISSUE TITLE
pipeline to publish pkgdown site

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#7]
basically, 

1. Recompile the vignettes by running `vignettes/precomile.R`. See #11 .
2. use pkgdown actions workflow or run `pkgdown::build_site()`

**Comment by j-i-l** [comment]
Hm, with https://github.com/furrer-lab/abn/blame/7c9dde07b875beb7266be35279170803047a74b8/.github/workflows/pkgdown.yaml#L44 we are using https://github.com/JamesIves/github-pages-deploy-action which pushes everything related to the site into a orphaned branch `gh-pages` (see https://github.com/furrer-lab/abn/network).
Unless you finally did opt for stuffing the pages into a branch, this might not be what we want.

I'd probably use the official actions to [configure pages](https://github.com/actions/configure-pages) and then [deploy them](https://github.com/actions/deploy-pages).
For an example see https://github.com/t4d-gmbh/working-with-git/blob/5d1c76e3060d0251082a530a1219025b8f6b6ec6/.github/workflows/pages.yml

**Comment by j-i-l** [comment]
> Now I messed up everything ^^ https://github.com/furrer-lab/abn/tree/33c22507e0412eab2952ff21c0f0b1c0fe0f7333

Good thing we are using git :smile:

**Comment by matteodelucchi** [comment]
looks like the page is created successfully as artifact but can't be published. This relates to https://github.com/furrer-lab/devel-abn/issues/107.

**Comment by j-i-l** [comment]
https://furrer-lab.github.io/abn/

**Comment by j-i-l** [comment]
next steps:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-user-site

in particular for step 5 you will need someone to edit the DNS records at the domain registrar

**Comment by j-i-l** [comment]
https://stackoverflow.com/questions/71113437/custom-domain-already-taken-error-in-github

**Comment by matteodelucchi** [comment]
The old page has been unpublished, so the DNS entries should be freed, but I still can't publish the custom domain. 

> https://stackoverflow.com/questions/71113437/custom-domain-already-taken-error-in-github

I will now follow the advice from your suggested SO post and contact GH support...

**Comment by j-i-l** [comment]
> The old page has been unpublished, so the DNS entries should be freed, but I still can't publish the custom domain.
> 
> > https://stackoverflow.com/questions/71113437/custom-domain-already-taken-error-in-github
> 
> I will now follow the advice from your suggested SO post and contact GH support...

I sah the 404 yesterday, it's some progress.
Contacting support seems the right thing to do!

**Comment by matteodelucchi** [comment]
Wow, they were fast with replying :-)
The site is live at https://r-bayesian-networks.org/
