### ISSUE TITLE
package archive as artifact

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#8]
Get the .tar.gz from the build command as an artifact. This eases the CRAN submission.

**Comment by j-i-l** [comment]
We might want to create a [Release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) whenever a new tag is pushed. There is e.g. [this action](https://github.com/marketplace/actions/create-release) to do so.

**Comment by j-i-l** [comment]
Sonehow the publishing action is not triggered

**Comment by j-i-l** [comment]
See #12
