### ISSUE TITLE
test only relevant tests in quicktest pipeline

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/abn#83]
Problem:
- Independent of the change, all tests are run in the quickest pipeline
- The CRANchecks like pipeline has the tests turned off, because they have been run before.

Solution:
- in the quickest pipeline, run only the corresponding test to the file that has been changed and only if a file in the directory `/R` has changed. 
- For changes in source code functions, for the moment, run all tests as it is hard to pick all R functions that call the respective C function.
- Turn complete testing on in the CRAN like test pipeline.

**Comment by j-i-l** [comment]
If changes in `src/` test all, otherwise test only changed files
