### ISSUE TITLE
Build PDF for the JOSS publication using their gh action

### ISSUE THREAD

**Issue by j-i-l** [furrer-lab/abn#92]
https://github.com/marketplace/actions/open-journals-pdf-generator

**Comment by matteodelucchi** [comment]
This has been implemented already on this branch: https://github.com/furrer-lab/abn/actions/workflows/build-joss-paper.yml

**Comment by j-i-l** [comment]
> @j-i-l This has been implemented already on this branch: https://github.com/furrer-lab/abn/actions/workflows/build-joss-paper.yml

Ha, I also realized that when looking at the JOSS branch. It could be that it was even me putting it there...
